
## Introduction to NumPy:

NumPy is a fundamental library for numerical computing in Python. It stands for "Numerical Python" and provides support for large, multi-dimensional arrays and matrices, along with an extensive collection of high-level mathematical functions to operate on these arrays efficiently. NumPy is the foundation for many scientific and data science libraries in Python and is widely used in various fields, such as data analysis, machine learning, and scientific research.

Installing NumPy:

If you don't have NumPy installed, you can install it using pip:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages. 



[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Importing NumPy:

To use NumPy in your Python code, you need to import it:

In [2]:
import numpy as np

## Creating NumPy Arrays:

NumPy arrays are similar to lists, but they can hold multi-dimensional data. Let's create some arrays to demonstrate its capabilities:

In [4]:
# 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


In [5]:
arr1d

array([1, 2, 3, 4, 5])

In [6]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Array Attributes:

NumPy arrays have useful attributes that provide information about their shape and data type:

In [31]:
arr = np.array([1, 2, 3, 4, 5])
print("Shape:", arr.shape)      
print("Data Type:", arr.dtype)  
print("Number of Dimensions:", arr.ndim)  


Shape: (5,)
Data Type: int32
Number of Dimensions: 1


In [41]:
lst = [1,2,3]
arr2 = np.array(lst)
arr2

array([1, 2, 3])

In [52]:
list1 = [1,2,3]
list2 = [2,3,4]
list3 = [5,6,7]

list_arr = np.array([list1,list2,list3])
list_arr

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [51]:
list_arr.shape

(3, 3)

## Array Operations:

NumPy allows performing element-wise operations on arrays, making computations faster and more efficient:

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
result_add = a + b

# Element-wise multiplication
result_mul = a * b

# Element-wise division
result_div = a / b

# Dot product (matrix multiplication)
dot_product = np.dot(a, b)

# Broadcasting: Applying operations on arrays with different shapes
broadcasting_example = a + 10


In [16]:
print('addition: ' , result_add)
print('multiplication: ' , result_mul)
print('division: ' , result_div)
print('matrix multiplication: ' , dot_product)
print('broadcasting_example: ' , broadcasting_example)


addition:  [5 7 9]
multiplication:  [ 4 10 18]
division:  [0.25 0.4  0.5 ]
matrix multiplication:  32
broadcasting_example:  [11 12 13]


## Array Indexing and Slicing:

You can access elements, rows, and columns in NumPy arrays using indexing and slicing:

In [18]:
arr = np.array([1, 2, 3, 4, 5])

# Accessing an element
print(arr[0])     # Output: 1

# Slicing
print(arr[1:4])   # Output: [2 3 4]

# 2D Array indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[1, 2])  # Output: 6 (element in the second row, third column)
print(arr2d[:, 1])  # Output: [2 5 8] (second column)

# Boolean indexing (filtering)
print(arr[arr > 2])  # Output: [3 4 5]


1
[2 3 4]
6
[2 5 8]
[3 4 5]


## differance b/w  Indexing and Slicing


**Indexing:**

Indexing refers to the process of accessing individual elements of an array using their position or index. In Python, indexing starts from 0, which means the first element of an array is accessed using index 0, the second element using index 1, and so on.

For example, let's consider the array `arr = [10, 20, 30, 40, 50]`. To access individual elements through indexing:

```python
arr[0]  # Output: 10 (First element)
arr[2]  # Output: 30 (Third element)
arr[-1] # Output: 50 (Last element)
```

**Slicing:**

Slicing is the process of extracting a portion (or subsequence) of an array. It allows you to create a new array containing a subset of the elements from the original array. Slicing is done by specifying a range of indices using the colon (:) operator.

The syntax for slicing is `array[start:stop:step]`, where:
- `start`: The index to start slicing (included in the slice).
- `stop`: The index to stop slicing (not included in the slice).
- `step`: The step size, i.e., the number of elements between each index in the slice (optional, default is 1).

For example, using the same array `arr = [10, 20, 30, 40, 50]`, let's see some slicing examples:

```python
arr[1:4]    # Output: [20, 30, 40] (Slice from index 1 to 3, not including 4)
arr[:3]     # Output: [10, 20, 30] (Slice from the beginning to index 2, not including 3)
arr[2:]     # Output: [30, 40, 50] (Slice from index 2 to the end)
arr[::2]    # Output: [10, 30, 50] (Slice with a step of 2, includes every second element)
arr[::-1]   # Output: [50, 40, 30, 20, 10] (Slice with a step of -1, reverses the array)
```

**Summary:**

In summary, indexing is used to access individual elements of an array by their specific position (index), while slicing is used to extract a portion of an array by specifying a range of indices. Indexing retrieves a single element, whereas slicing creates a new array containing a subset of elements from the original array based on the specified range. Both indexing and slicing are powerful tools for working with arrays and are commonly used in Python for data manipulation and analysis.

In [54]:
#indexing
arr = np.array([1,2,3,4])
arr[3]

4

In [56]:
# assgin index[3] to 5 number 
arr[3]=5
arr

array([1, 2, 3, 5])

In [57]:
# -1 means last item 

arr[-1]

5

In [67]:
#  all to last, last will not shown 
arr[:-1]

array([1, 2, 3])

In [71]:
# :: all, with gape of 3 numbers

arr2 = [1,2,3,4,5,6,7,8,9,10,11]
arr2[::3]

[1, 4, 7, 10]

In [73]:
#  reverse and 3 num gap
arr2[::-3]   

[11, 8, 5, 2]

## Indexing in 2D

Indexing in 2D refers to the process of accessing elements in a two-dimensional array using row and column indices. In a 2D array, elements are organized in rows and columns, forming a grid-like structure. The indexing notation for a 2D array is `array[row_index, column_index]`, where `row_index` is the index of the row, and `column_index` is the index of the column.

Let's consider a simple 2D array as an example:

```python

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

To access individual elements in the 2D array:

```python
# Accessing a single element
element_1 = arr_2d[0, 0]  # First row, first column (Output: 1)
element_2 = arr_2d[1, 2]  # Second row, third column (Output: 6)
element_3 = arr_2d[2, 1]  # Third row, second column (Output: 8)
```

To access entire rows or columns:

```python
# Accessing an entire row
row_1 = arr_2d[0, :]  # First row (Output: [1 2 3])
row_2 = arr_2d[1, :]  # Second row (Output: [4 5 6])
row_3 = arr_2d[2, :]  # Third row (Output: [7 8 9])

# Accessing an entire column
col_1 = arr_2d[:, 0]  # First column (Output: [1 4 7])
col_2 = arr_2d[:, 1]  # Second column (Output: [2 5 8])
col_3 = arr_2d[:, 2]  # Third column (Output: [3 6 9])
```

You can also perform slicing in 2D arrays to extract a sub-matrix:

```python
# Slicing a sub-matrix
sub_matrix = arr_2d[1:3, 1:3]
# Output:
# [[5 6]
#  [8 9]]
```

In this example, we sliced the 2D array `arr_2d` to create a sub-matrix containing the elements from rows 1 to 2 and columns 1 to 2.

By using appropriate row and column indices, you can efficiently access specific elements or sub-matrices within a 2D array for various data analysis and manipulation tasks.

In [164]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [192]:
arr_2d[1,2]

6

In [189]:
arr_2d[1,:2]

array([4, 5])

In [188]:
arr_2d[1:,2]

array([6, 9])

In [193]:
arr_2d[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [194]:
arr_2d[::]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [200]:
arr_2d[2,:1]

array([7])

In [209]:
arr_2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [210]:
arr_2d[:2,1]

array([2, 5])

## Let's break down the slicing expression `arr[:2, 1]`:

Assuming `arr` is a 2D array:

```python
import numpy as np

# Example 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

**Slicing Explanation:**

1. `arr[:2, 1]`:

- `:2` represents the row slicing, and it means that we want to select rows from the beginning (index 0) up to, but not including, the row with index 2. In other words, it selects the first two rows (rows 0 and 1) of the 2D array.
- `,` separates the row and column slicing.
- `1` represents the column slicing, and it means that we want to select elements from the second column (index 1) of the specified rows.

**Output:**

The slicing expression `arr[:2, 1]` will return a 1D array containing the elements from the second column of the first two rows (rows 0 and 1) of the original 2D array:

```python
output = arr[:2, 1]

# Output: [2 5]
```

In this example, the output is `[2 5]`, which represents the values `2` and `5`. These values are taken from the second column (index 1) of the first two rows (rows 0 and 1) of the `arr` array.

In summary, `arr[:2, 1]` slices the 2D array to select specific elements from the first two rows and the second column, resulting in a 1D array containing the selected elements.

In [211]:
arr_2d[:2,1]

array([2, 5])

## Let's break down the slicing expression `arr[2:, 1]`:

Assuming `arr` is a 2D array:

```python

# Example 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

**Slicing Explanation:**

1. `arr[2:, 1]`:

- `2:` represents the row slicing, and it means that we want to select rows starting from index 2 and all the way to the end. In other words, it selects the last row (row with index 2) and all rows after it.
- `,` separates the row and column slicing.
- `1` represents the column slicing, and it means that we want to select elements from the second column (index 1) of the specified rows.

**Output:**

The slicing expression `arr[2:, 1]` will return a 1D array containing the elements from the second column (index 1) of all rows starting from the third row (row with index 2) to the end of the original 2D array:

```python
output = arr[2:, 1]

# Output: [8]
```

In this example, the output is `[8]`, which represents the value `8`. This value is taken from the second column (index 1) of the last row (row with index 2) of the `arr` array.

In summary, `arr[2:, 1]` slices the 2D array to select specific elements from all rows starting from the third row (row with index 2) and the second column, resulting in a 1D array containing the selected elements.

In [201]:
arr_2d[2,:]

array([7, 8, 9])

Sure! Let's break down the indexing expression `arr_2d[2, :]`:

Assuming `arr_2d` is a 2D array:

```python
import numpy as np

# Example 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

**Indexing Explanation:**

1. `arr_2d[2, :]`:

- `2` represents the row index, and it means that we want to access the third row of the 2D array. In Python, indexing starts from 0, so `2` corresponds to the third row.
- `,` separates the row and column indices.
- `:` after the comma represents the column slicing. It means we want to select all elements from the specified row.

**Output:**

The indexing expression `arr_2d[2, :]` will return a 1D array containing all elements from the third row (row with index 2) of the original 2D array:

```python
output = arr_2d[2, :]

# Output: [7 8 9]
```

In this example, the output is `[7 8 9]`, which represents the entire third row of the `arr_2d` array.

In summary, `arr_2d[2, :]` indexes the 2D array to access the third row (row with index 2) and returns a 1D array containing all the elements from that row.

In [202]:
arr_2d[2,:2]

array([7, 8])

## Let's break down the slicing expression `arr_2d[2, :2]`:

Assuming `arr_2d` is a 2D array:

```python
import numpy as np

# Example 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

**Slicing Explanation:**

1. `arr_2d[2, :2]`:

- `2` represents the row index, and it means that we want to access the third row of the 2D array. In Python, indexing starts from 0, so `2` corresponds to the third row.
- `,` separates the row and column indices.
- `:2` after the comma represents the column slicing. It means we want to select elements from the specified row up to, but not including, the column with index 2.

**Output:**

The slicing expression `arr_2d[2, :2]` will return a 1D array containing the first two elements from the third row (row with index 2) of the original 2D array:

```python
output = arr_2d[2, :2]

# Output: [7 8]
```

In this example, the output is `[7 8]`, which represents the first two elements from the third row of the `arr_2d` array.

In summary, `arr_2d[2, :2]` slices the 2D array to select specific elements from the third row (row with index 2) up to, but not including, the column with index 2, resulting in a 1D array containing the selected elements.

In [203]:
arr_2d[2,:3]

array([7, 8, 9])

In [205]:
arr_2d[1,:3]

array([4, 5, 6])

In [206]:
arr_2d[2,:1]

array([7])

In [166]:
# Accessing a single element
element_1 = arr_2d[0, 0]  # First row, first column (Output: 1)
element_1

1

In [167]:
arr_2d[1, 2]  # Second row, third column (Output: 6)

6

In [168]:
arr_2d[2, 1]  # Third row, second column (Output: 8)

8

In [ ]:
# To access entire rows or columns:

# Accessing an entire row
row_1 = arr_2d[0, :]  # First row (Output: [1 2 3])
row_2 = arr_2d[1, :]  # Second row (Output: [4 5 6])
row_3 = arr_2d[2, :]  # Third row (Output: [7 8 9])

# Accessing an entire column
col_1 = arr_2d[:, 0]  # First column (Output: [1 4 7])
col_2 = arr_2d[:, 1]  # Second column (Output: [2 5 8])
col_3 = arr_2d[:, 2]  # Third column (Output: [3 6 9])

In [169]:
# Second row (Output: [4 5 6])
row_2 = arr_2d[1, :]  
row_2

array([4, 5, 6])

In [171]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
col_3 = arr_2d[:, 2]  # Third column (Output: [3 6 9])
col_3

array([3, 6, 9])

In [179]:
col_4 = arr_2d[1:2]
col_4

array([[4, 5, 6]])

In [181]:
# Slicing a sub-matrix
sub_matrix = arr_2d[1:3, 1:3]
sub_matrix

array([[5, 6],
       [8, 9]])

In [184]:
# Slicing a sub-matrix
sub_matrix = arr_2d[1:3]
sub_matrix

array([[4, 5, 6],
       [7, 8, 9]])

In [134]:
# Slicing
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
arr[1:4]

array([[4, 5, 6],
       [7, 8, 9]])

In [142]:
arr[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [147]:
new_arr = np.arange(1,40,2).reshape(4,5)
new_arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [158]:
new_arr[2:3]

array([[21, 23, 25, 27, 29]])

In [161]:
new_arr[2,:3]

array([21, 23, 25])

In [151]:
new_arr[1:4]

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [156]:
new_arr[3:1]

array([], shape=(0, 5), dtype=int32)

## Array Shape Manipulation:

NumPy allows you to manipulate the shape of arrays easily:

In [99]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reshape the array
reshaped = arr.reshape(1, 9)

# Transpose the array
transposed = arr.T

# Flatten the array
flattened = arr.flatten()

# Concatenation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concatenated = np.concatenate((a, b))

print('array: ' , "\n" , arr , "\n")
print('reshaped: ')
print( reshaped, "\n")
print('transposed: ')
print( transposed, "\n")
print('flattened: ')
print( flattened, "\n")
print('concatenated: ')
print( concatenated)


array:  
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

reshaped: 
[[1 2 3 4 5 6 7 8 9]] 

transposed: 
[[1 4 7]
 [2 5 8]
 [3 6 9]] 

flattened: 
[1 2 3 4 5 6 7 8 9] 

concatenated: 
[1 2 3 4 5 6]


In [93]:
# Transpose the array
transposed = arr.T
transposed

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [94]:
# Flatten the array
flattened = arr.flatten()
flattened

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
# Concatenation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concatenated = np.concatenate((a, b))
concatenated

array([1, 2, 3, 4, 5, 6])

In [110]:
# Reshape the array
reshaped = arr.reshape(1, 9)
reshaped

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [116]:
reshaped.shape

(1, 9)

In [120]:
reshaped.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## how much possible ways to reshape this? 
To find out the possible ways to reshape the array `arr` into a 1-dimensional array of 9 elements, we can check how many combinations of dimensions result in a total of 9 elements. Reshaping an array means changing its dimensions while keeping the total number of elements constant.

For `arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, the original shape is (3, 3), and we want to reshape it into a 1-dimensional array with 9 elements.

To get a 1-dimensional array with 9 elements, the possible reshapes are:

1. (9,)
2. (1, 9)
3. (3, 3)
4. (3, 1, 3)
5. (3, 3, 1)
6. (1, 1, 9)
7. (1, 3, 3)
8. (1, 3, 1, 3)
9. (1, 3, 3, 1)
10. (1, 1, 1, 9)
11. (1, 1, 3, 3)
12. (1, 1, 1, 3, 3)
13. (1, 1, 3, 1, 3)
14. (1, 1, 3, 3, 1)
15. (1, 1, 1, 1, 1, 9)
16. (1, 1, 1, 1, 3, 3)
17. (1, 1, 1, 1, 1, 3, 3)
18. (1, 1, 1, 1, 1, 3, 1, 3)
19. (1, 1, 1, 1, 1, 3, 3, 1)
20. (1, 1, 1, 1, 1, 1, 1, 1, 9)

So, there are a total of 20 possible ways to reshape the array `arr` into a 1-dimensional array with 9 elements.

In [122]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
arr.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
arr.reshape(1, 1, 3, 1, 3)

array([[[[[1, 2, 3]],

         [[4, 5, 6]],

         [[7, 8, 9]]]]])

In [128]:
arr.reshape(1, 3, 3, 1)

array([[[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]]])

In [102]:
# other way to make array

lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])
arr1


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [103]:
arr1.shape

(3, 5)

In [114]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [104]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
## mechanism to create an array

np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [130]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

## Mathematical Functions:

NumPy provides a wide range of mathematical functions that can be applied element-wise:

In [21]:
arr = np.array([1, 2, 3, 4, 5])

# Square root
sqrt_arr = np.sqrt(arr)

In [213]:
sqrt_arr

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [214]:
# Exponential
exp_arr = np.exp(arr)
exp_arr

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [215]:
# Trigonometric functions
sin_arr = np.sin(arr)
cos_arr = np.cos(arr)

In [216]:
sin_arr

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [217]:
cos_arr

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

## Broadcasting:

Broadcasting allows NumPy to perform operations on arrays with different shapes:

In [131]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

result = a + b
result

array([[11, 22],
       [13, 24]])

## Array Aggregation:

NumPy provides functions for aggregation operations like sum, mean, min, max, etc.:

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [219]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [223]:
sum_all = arr.sum()
sum_axis0 = arr.sum(axis=0)
sum_axis1 = arr.sum(axis=1)

print(sum_axis0)
print(sum_axis1)

[12 15 18]
[ 6 15 24]


In [226]:

mean_all = arr.mean()
mean_axis0 = arr.mean(axis=0)
mean_axis1 = arr.mean(axis=1)

print(mean_axis0)
print(mean_axis1)

[4. 5. 6.]
[2. 5. 8.]


In [227]:
min_all = arr.min()
min_axis0 = arr.min(axis=0)
min_axis1 = arr.min(axis=1)

print(min_axis0)
print(min_axis1)

[1 2 3]
[1 4 7]


In [228]:

max_all = arr.max()
max_axis0 = arr.max(axis=0)
max_axis1 = arr.max(axis=1)

print(max_axis0)
print(max_axis1)

[7 8 9]
[3 6 9]


## Linear Algebra:

NumPy provides linear algebra functions for matrix operations:

In [24]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [231]:
# Matrix inverse
inv_a = np.linalg.inv(a)
inv_a

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [229]:
# Matrix multiplication
mat_mul = np.matmul(a, b)
mat_mul

array([ 50, 110])

In [230]:
# Matrix determinant
det_a = np.linalg.det(a)
det_a

-2.0000000000000004

## NumPy Random Module:

NumPy offers a random module for generating random numbers and random sampling:

In [232]:
# Random integers between a range
rand_int = np.random.randint(1, 10, size=(3, 3))
rand_int

array([[9, 1, 3],
       [4, 5, 6],
       [6, 1, 4]])

In [233]:
# Random numbers from a uniform distribution [0, 1)
rand_uniform = np.random.rand(3, 3)
rand_uniform

array([[0.04299792, 0.83548685, 0.46850895],
       [0.4970294 , 0.98715751, 0.61272486],
       [0.90594709, 0.81819597, 0.86577838]])

In [234]:
# Random numbers from a standard normal distribution (mean=0, variance=1)
rand_normal = np.random.randn(3, 3)
rand_normal

array([[ 2.04476754, -0.09639127,  0.72198686],
       [ 0.74571954,  0.22001069,  0.49687652],
       [ 1.5724904 , -0.61905045,  0.24115006]])

These are just some of the fundamental features and functionalities of NumPy. There is much more to explore, including advanced indexing, broadcasting with different shapes, and more sophisticated linear algebra functions. NumPy's documentation is a great resource to dive deeper into the library and learn about its full capabilities.




